### ISSUE TITLE
[BACK] Endpoint de remoção de orientador do aluno

### ISSUE THREAD

**Issue by tauanesales** [tauanesales/Sistema-PGCop-UFBA#75]
# TODO:
- [x] Criar endpoint de PUT `/alunos/remover-orientador`;
- [x] Receber apenas o parâmetro `aluno_id` no body;
- [x] Autenticar rota;
- [x] Checar se o token do usuário pertence ao tipo professor ou coordenador (se não pertencer, levantar exceção `NaoAutorizadoException`;
- [x] Se o usuário for autorizado a remover o orientador, trocar o ID do orientador do aluno para ID 1 (será um professor padrão, chamado "Sem Orientador");

# Critério de aceite do PR
No PR, deve ser submetido um print batendo no endpoint localmente e ele respondendo dentro do esperado.
Escrever "FIXES #75" na descrição do PR.
